// dojo_frontend_base/javascript_react/src/Link.js
import React from 'react';

const status = {
    NORMAL: 'link-normal',
    HOVERED: 'link-hovered',
};

export default class Link extends React.Component{
    constructor(props) {
        super(props);

        this._onMouseEnter = this._onMouseEnter.bind(this);
        this._onMouseLeave = this._onMouseLeave.bind(this);

        this.state = {
            className: status.NORMAL
        };
    }

    _onMouseEnter() {
        this.setState({className : status.HOVERED})
    }

    _onMouseLeave() {
        this.setState({className : status.NORMAL})
    }

    render() {
        return (
            <a
            className={this.state.className}
            href={this.props.page}
            onMouseEnter={this._onMouseEnter}
            onMouseLeave={this._onMouseLeave}>
                {this.props.children}
            </a>
        );
    }
}

// dojo_frontend_base/javascript_vue/src/link.vue
<template>
    <a v-bind:href={page}
       v-bind:class={className}
       v-on:mouseEnter="handleMouseEnter"
       v-on:mouseLeave="handleMouseLeave"
    >{{text}}</a>
</template>

<script>
    const status = {
        NORMAL: 'link-normal',
        HOVERED: 'link-hovered'
    };
    export default {
        props: ['page', 'text'],
        data() {
            return {
                className: status.NORMAL
            };
        },

        methods: {
            handleMouseEnter(){
                this.className = status.HOVERED;
            },
            handleMouseLeave(){
                this.className = status.NORMAL;
            }
        },

        created(){
            this.page = 'google.com.ar'
        }
    }
</script>
